# Site settings
title: "The boring CS Blog"
description: "A guy that is trying to make computer science a little more fun."
baseurl: "" 
url: "https://toborochi.github.io/"
author: "Leonardo Añez Vladimirovna"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
